### ISSUE TITLE
Can't get OSX-arm64/ca6502Debugger to run

### ISSUE THREAD

**Issue by mslinklater** [OldSkoolCoder/6502-For-Beginners-Book#1]
I've set it to executable... but whenever I try to run it I get:

link@Martins-MacBook-Air OSX-arm64 % ./ca6502Debugger 
zsh: killed     ./ca6502Debugger

Are there some command line switches or required installs I'm missing ?

**Comment by mslinklater** [comment]
Just tried the OSX-x64 one and that runs.

**Comment by OldSkoolCoder** [comment]
Ok, I had a friend check the program, and apparently this is whats the issue.

"ok the issue is the code MUST be signed even if its a self signed cert for it to run on apple silicon. The user will get an error on 1st run BUT they can go into control panel -> security and click trust then it will work"
